### ISSUE TITLE
Webpack Comiling Error

### ISSUE THREAD

**Issue by unlogicalcode** [AignerM/angular5_Presentation#2]
ng serve funtioniert nicht aufgrund von Komillierfehlerern die durch das zusammenspiel von Materialize-CSS erzeugt werden. 

`ERROR in multi ./src/styles.css ./node_module/materialze-css/dist/css/materialize.css
Module not found: Error: Can't resolve '/home/unlogicalcode/Programmieren/angular5_Presentation/angular5-prasentation/node_module/materialze-css/dist/css/materialize.css' in '/home/unlogicalcode/Programmieren/angular5_Presentation/angular5-prasentation/node_modules/@angular/cli/models/webpack-configs'
resolve '/home/unlogicalcode/Programmieren/angular5_Presentation/angular5-prasentation/node_module/materialze-css/dist/css/materialize.css' in '/home/unlogicalcode/Programmieren/angular5_Presentation/angular5-prasentation/node_modules/@angular/cli/models/webpack-configs'
  using description file: /home/unlogicalcode/Programmieren/angular5_Presentation/angular5-prasentation/node_modules/@angular/cli/package.json (relative path: ./models/webpack-configs)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /home/unlogicalcode/Programmieren/angular5_Presentation/angular5-prasentation/node_modules/@angular/cli/package.json (relative path: ./models/webpack-configs)
    using description file: /home/unlogicalcode/Programmieren/angular5_Presentation/angular5-prasentation/package.json (relative path: ./node_module/materialze-css/dist/css/materialize.css)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /home/unlogicalcode/Programmieren/angular5_Presentation/angular5-prasentation/node_module/materialze-css/dist/css/materialize.css doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /home/unlogicalcode/Programmieren/angular5_Presentation/angular5-prasentation/node_module/materialze-css/dist/css/materialize.css.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /home/unlogicalcode/Programmieren/angular5_Presentation/angular5-prasentation/node_module/materialze-css/dist/css/materialize.css.js doesn't exist
      as directory
        /home/unlogicalcode/Programmieren/angular5_Presentation/angular5-prasentation/node_module/materialze-css/dist/css/materialize.css doesn't exist
[/home/unlogicalcode/Programmieren/angular5_Presentation/angular5-prasentation/node_module/materialze-css/dist/css/materialize.css]
[/home/unlogicalcode/Programmieren/angular5_Presentation/angular5-prasentation/node_module/materialze-css/dist/css/materialize.css.ts]
[/home/unlogicalcode/Programmieren/angular5_Presentation/angular5-prasentation/node_module/materialze-css/dist/css/materialize.css.js]
[/home/unlogicalcode/Programmieren/angular5_Presentation/angular5-prasentation/node_module/materialze-css/dist/css/materialize.css]
 @ multi ./src/styles.css ./node_module/materialze-css/dist/css/materialize.css`

**Comment by AignerM** [comment]
versuchs nochmal mit npm install normal sollte es so gehen

**Comment by unlogicalcode** [comment]
habe ich bereits auf mehren Maschinen reproduzierbarer fehler, inclusive nem komplett frischen clone

**Comment by AignerM** [comment]
ja ich hab jetzt den Fehler gefunden... Materialize ist in master nicht in der package.json drin

**Comment by AignerM** [comment]
okay jetzt bekomm ich den fehler auch

**Comment by unlogicalcode** [comment]
this was the moment he knew we fucked up

**Comment by AignerM** [comment]
sollte jetzt passen probiers mal

**Comment by unlogicalcode** [comment]
confirmative
